language: node_js

node_js:
  - "node"
  - "7"

script:
  - npm run ci:travis

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  yarn: true

notifications:
  email: true
