sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "node"
  - "7"
script:
  - npm run ci:travis
cache:
  yarn: true
notifications:
  email: false
